// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book_query.sql

package codegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
	author_id, title, summary, published_at
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, author_id, title, summary, published_at
`

type CreateBookParams struct {
	AuthorID    int64
	Title       string
	Summary     pgtype.Text
	PublishedAt pgtype.Date
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.AuthorID,
		arg.Title,
		arg.Summary,
		arg.PublishedAt,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Summary,
		&i.PublishedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, author_id, title, summary, published_at FROM books
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Summary,
		&i.PublishedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, author_id, title, summary, published_at FROM books
ORDER BY title
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Summary,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksByAuthor = `-- name: ListBooksByAuthor :many
SELECT id, author_id, title, summary, published_at FROM books
WHERE author_id = $1
ORDER BY title
`

func (q *Queries) ListBooksByAuthor(ctx context.Context, authorID int64) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooksByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Summary,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET author_id = $2,
		title = $3,
		summary = $4,
		published_at = $5
WHERE id = $1
RETURNING id, author_id, title, summary, published_at
`

type UpdateBookParams struct {
	ID          int64
	AuthorID    int64
	Title       string
	Summary     pgtype.Text
	PublishedAt pgtype.Date
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Summary,
		arg.PublishedAt,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Summary,
		&i.PublishedAt,
	)
	return i, err
}
