// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: author_query.sql

package codegen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO author (
  name, bio
) VALUES (
  $1, $2
)
RETURNING id, publisher_id, name, bio
`

type CreateAuthorParams struct {
	Name string
	Bio  pgtype.Text
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Name,
		&i.Bio,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM author
WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT author.id, author.publisher_id, author.name, author.bio, publisher.id, publisher.name
FROM author
JOIN publisher ON author.publisher_id = publisher.id
WHERE author.id = $1 LIMIT 1
`

type GetAuthorRow struct {
	Author    Author
	Publisher Publisher
}

func (q *Queries) GetAuthor(ctx context.Context, id int64) (GetAuthorRow, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i GetAuthorRow
	err := row.Scan(
		&i.Author.ID,
		&i.Author.PublisherID,
		&i.Author.Name,
		&i.Author.Bio,
		&i.Publisher.ID,
		&i.Publisher.Name,
	)
	return i, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT author.id, author.publisher_id, author.name, author.bio, publisher.id, publisher.name
FROM author
JOIN publisher ON author.publisher_id = publisher.id
ORDER BY author.name
`

type ListAuthorsRow struct {
	Author    Author
	Publisher Publisher
}

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorsRow
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.Author.ID,
			&i.Author.PublisherID,
			&i.Author.Name,
			&i.Author.Bio,
			&i.Publisher.ID,
			&i.Publisher.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE author
  set name = $2,
  bio = $3
WHERE id = $1
RETURNING id, publisher_id, name, bio
`

type UpdateAuthorParams struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor, arg.ID, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.PublisherID,
		&i.Name,
		&i.Bio,
	)
	return i, err
}
