// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package codegen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID          int64
	PublisherID int64
	Name        string
	Bio         pgtype.Text
}

type Publisher struct {
	ID   int64
	Name string
}
